spring:
 redis:
   host: localhost
   port: 6379
   password:
   database: 1
   timeout: 30
 jackson:
   date-format: yyyy-MM-dd hh:mm:ss
   time-zone: GMT+8
 datasource:
    url: jdbc:sqlserver://192.168.6.130:1433;databaseName=SLYT
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: HJZ__++318
    data:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

 jpa:
  show-sql: true
  database: sql_server
  properties:
   hibernate:
    dialect : org.hibernate.dialect.SQLServer2008Dialect
  hibernate:
     ddl-auto: update
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 mvc:
   view:
     suffix: .jsp
     prefix: /WEB-INF/webapp

#mybatis:
 #type-aliases-package:com.hdkj.lyt.hnlyt_fire.repository


server:
  port: 8099
  servlet:
    path: /HNLYT
  tomcat:
    uri-encoding: utf-8

logging:
  path: /hnlyt/log
  level:
   com.hdkj.lyt.hnlyt_fire.repository: debug
mybatis:
    #configuration:
      #map-underscore-to-camel-case: true
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.hdkj.lyt.hnlyt_fire.repository
   # config-location: classpath:/mybatis/mybatis-config.xml




